/**
 * Departamentos.gs — mapeamento assunto do ticket -> departamento.
 * Gerado a partir de Departamentos.xlsx. Assuntos sem match viram "Sem Departamento".
 * Para alterar: edite aqui ou regenere a partir da planilha.
 */
const DEPARTAMENTOS = {
  "Operações - Validação de PPs": "Operações",
  "Análise Paga - Contrato do cliente": "Operações",
  "W1 Capital - Transferência de Clientes | Mesa Digital": "Capital",
  "Produtos Parceiras - Pendências de Seguro de Vida": "Operações",
  "Análise Paga - Pagamento do cliente": "Operações",
  "Fiscal - Alteração de dados cadastrais": "Financeiro",
  "Treinamento & Desenvolvimento": "Treinamento & Desenvolvimento",
  "Comissões": "Financeiro",
  "CS/CX - Transferência de clientes": "CS/CX",
  "CS/CX - W1 Acompanhamento (Cancelamento)": "CS/CX",
  "Produtos Parceiras - Acompanhamento, Envio de Formulários e Cancelamento": "Operações",
  "CS/CX - W1 Acompanhamento (Cobrança /Dúvidas Gerais)": "CS/CX",
  "CS/CX - BP Out": "CS/CX",
  "W1 Capital - Saída de Assessor": "Capital",
  "W1 Capital - Transferência de Clientes": "Capital",
  "W1 Capital - Transferência de custódia | STVM | Portabilidade": "Capital",
  "Performance Comercial - Brindes e Promoções": "Performance comercial",
  "CS/CX - Solicitação de Acesso Binds (APENAS PARA PARTNERS)": "CS/CX",
  "CS/CX - Pendência da 1ª Parcela de Seguro de Vida": "CS/CX",
  "Jurídico - Dúvidas sobre Liberação de BP no W1nner": "Jurídico",
  "Comprovante de Pagamento Pix": "Fianceiro",
  "Jurídico - Solicitação de Contrato de BP e Cópia do Distrato": "Jurídico",
  "Erro de Sistema - W1nner": "Operações",
  "Fiscal - Solicitação de pagamento de NF - Cancelamento de NF": "Fianceiro",
  "CS/CX - Inadimplência Seguro de Vida": "CS/CX",
  "Financeiro - Pagamento de BP e Assessor": "Financeiro",
  "Operações - Erro de Sistema das Parceiras": "Operações",
  "CS/CX - Inadimplência Consórcio": "CS/CX",
  "Operações - Automatização de Reports": "Operações",
  "Jurídico - Duvidas sobre Contratos de BP": "Jurídico",
  "Problemas de Acesso W1nner": "Fianceiro",
  "E-mail Marketing": "Marketing",
  "Análise Paga - Dúvidas sobre pagamento do cliente": "Operações",
  "W1 Capital - Comissões PJ2": "Capital",
  "teste": "teste",
  "Fiscal - Solicitação de pagamento de NF - Valor divergente da NF": "Fianceiro",
  "W1 Capital - Abertura de conta PJ": "Capital",
  "Esclarecimentos Jurídicos – Assessoria de Investimento": "Jurídico",
  "Jurídico - Solicitação de Cópia de Documentos": "Jurídico",
  "Jurídico - Solicitação de Contrato de Parceria": "Jurídico",
  "CS/CX - Inadimplência de Previdência": "CS/CX",
  "Financeiro - AP e Dúvidas de AP": "Financeiro",
  "W1 Capital - Botão vermelho XP": "Capital",
  "Operações - W1 Consultoria Patrimonial": "Operações",
  "W1 Capital - Demandas Taylor": "Capital",
  "Leads Marketing": "Marketing",
  "Funil de Expansão - Problemas Gerais": "Expansão comercial"
};
